/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {
    private ArrayList<Tarefa> tarefas = new ArrayList<>();

    public static void main(String[] args) {
        App app = new App();

        app.tarefas.add(new Tarefa("AtividadePOO", LocalDate.of(2024,7,1)));
        app.tarefas.forEach(tarefa -> System.out.println(tarefa));    }
}
