/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {
    private ArrayList<Tarefa> tarefa = new ArrayList<>();

    public static void main(String[] args) {
        App app = new App();

        app.tarefa.add(new Tarefa("AtividadePOO", LocalDate.of(2024,7,1)));

        //for each aqui

    }
}
