/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;
import java.awt.*;

public class App {
    public static void main(String[] args) {
        Draw draw = new Draw("Luan");
        //draw.clear(Color.CYAN);
        //draw.setPenColor(Color.CYAN);
        //draw.filledSquare(.5,.5,.5);
        //draw.setPenColor(Color.BLACK);
        //draw.text(.5,.5,"Ola Bruno");

        //abriu outra janela
        draw.setCanvasSize(800,800);
        draw.setXscale(0,800);
        draw.setYscale(0,800);

        draw.setPenColor(Color.BLUE);
        draw.filledCircle(400,400,100);

        draw.picture(500,500, "mito.jpg");
    }
}
