/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo.produtos;
import engtelecom.poo.produtos.AparelhoTelefonico;
import engtelecom.poo.produtos.SemFio;
import engtelecom.poo.produtos.Telefone;
import engtelecom.poo.produtos.Tamanho;

public class App {

    public static void main(String[] args) {

        /*Tamanho t = new Tamanho(0.05, 0.1, 0.01);
        AparelhoTelefonico tl = new AparelhoTelefonico("E5DS.4GW", 458862356, "TL1", "Preto", 0.12, t);

        System.out.println(tl.toString());

        SemFio sf = new SemFio("VSD56R41G", 453158, "TSF1", "Preto", 0.15, t, 8000, 5, 20);

        System.out.println(sf.toString());
        System.out.println(sf.imprimirDados());*/
        Telefone telefone = new Telefone();
        SemFio sf = new SemFio();
        Celular celular = new Celular();

    }
}
