/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    
    public static void main(String[] args) {
        Ponto a = new Ponto(5, 5);
        Ponto b = new Ponto(10, 10);

        System.out.println("distancia de a para b " + a.distancia(b));
        System.out.println("distancia de b para a " + b.distancia(a));
    }
}
