/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Scanner;

public class App {

    private HashMap<String,Aluno> bancoDeDados;
    private static Scanner teclado = new Scanner(System.in);

    public App() {
        this.bancoDeDados = new HashMap<String,Aluno>();
    }

    public boolean cadastrar(){
        /*LocalDate data = LocalDate.of(2000,10,20);

        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/mm/yyyy");
        String d = "20/10/2024";
        data = LocalDate.parse(d,df);*/

        //luno aluno = new Aluno();

        System.out.println("cadastrando aluno");

        return true;
    }

    public void atualizar(){

        System.out.println("atualizando aluno");
    }

    public boolean remover(){
        System.out.println("removido");
        return true;
    }

    public void listarDadosUmAluno(){
        System.out.println("listando");
    }

    public void listarDadosTodosAlunos(){
        System.out.println("listando");
    }

    public int menu(){
        System.out.println("sigaa");
        System.out.println("1- Cadastrar");
        System.out.println("2- Atualizar");
        System.out.println("3- Remover");
        System.out.println("4- Listar dados de um aluno");
        System.out.println("5- Listar todos os alunos");
        System.out.println("6- Sair");

        return teclado.nextInt();
    }

    public static void main(String[] args) {
        App app = new App();
        int opcao;

        do {
            opcao = app.menu();

            switch (opcao) {
                case 1 -> app.cadastrar();
                case 2 -> app.atualizar();
                case 3 -> app.remover();
                case 4 -> app.listarDadosUmAluno();
                case 5 -> app.listarDadosTodosAlunos();
            }
        } while (opcao != 6);

        System.out.println("finalizando");
    }
}
