/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {

        /**
         * CONTADOR
         */
//        Contador a = new Contador();
//        Contador b = new Contador();
//
//        a.incrementar();
//        System.out.println("Contador A: " + a.getValorAtual());
//
//        for (int i = 0; i < 7; i++) {
//            a.incrementar();
//            System.out.println("Contador A: " + a.getValorAtual());
//        }

        /**
         * CANETA BIC
         */

//        Caneta bic = new Caneta();
//
//        bic.setCor("azul");
//        bic.setNivelTinta(100);
//        bic.abrirFechar();
//        bic.desenhar();
//
//        Caneta pilot = new Caneta();
//        pilot.setCor("preta");
//        pilot.setNivelTinta(1);

        /**
         * BUZZ LIGHTYEAR
         */

        Buzz buzz = new Buzz();
        buzz.abrirFecharCapacete();
        System.out.println(buzz.falar());

        /*Pessoa[] vetor = new Pessoa[10];

        Pessoa juca = new Pessoa();
        juca.setCpf("123546897-89");
        juca.setEmail("juca.bento@gmail.com");
        juca.setEndereco("Rua Pasqualino Ferraz, 128");
        juca.setNome("Juca Bento");
        juca.setSexo("Maascho");
        juca.setTelefone("4896214978");

        System.out.println("Nome: " + juca.getNome());
        System.out.println("cpf: " + juca.getCpf());
        System.out.println("email: " +  juca.getEmail());
        System.out.println("Endereco: " + juca.getEndereco());
        System.out.println("blablaaaaaaaaaaaaa");
        System.out.println(juca);

        Pessoa fulando = new Pessoa();

        for (int i = 0; i < vetor.length; i++) {
            //TODO
        }

        for (Pessoa p : vetor){
            System.out.println(p+"\n");
        }*/
    }
}
