/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom;

public class App {
    public static void main(String[] args) {
        /*DiaDaSemana[] d = {DiaDaSemana.SEG,DiaDaSemana.QUA};

        Disciplina poo = new Disciplina("poo", d);
        System.out.println(poo);

        for(DiaDaSemana a : DiaDaSemana.values()){
            System.out.println(a);
        }*/

        Planeta [] planetas = {Planeta.TER, Planeta.JUP};
        System.out.println(planetas);

        for (int i = 0; i < planetas.length; i++) {
            System.out.println(planetas[i]);
        }

        /*for (Planeta planeta : planetas) {
            System.out.println(planeta);
        }*/
    }
}
