/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Arqueiro arqueiro = new Arqueiro();
        Aldeao aldeao = new Aldeao();
        Cavaleiro cavaleiro = new Cavaleiro();

        System.out.println(arqueiro.mover());
        System.out.println(arqueiro.atacar());

        System.out.println(aldeao.atacar());
        System.out.println(aldeao.mover());

        System.out.println(cavaleiro.atacar());
        System.out.println(cavaleiro.mover());
    }
}
