/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        //banco de dado de autores
        //banco de dado de livros

        ArrayList<Autor> autores = new ArrayList<>();

        Autor jean = new Autor("Jean Maaczinky","França", LocalDate.of(1975,10,3));
        autores.add(jean);
        Autor mirna = new Autor("Mirna Schutz","Alemanha", LocalDate.of(1985,8,3));
        autores.add(mirna);

        Livro onceATime = new Livro("978658999013", "Once a time", autores);

        //se fizer desse jeito, cada autor adicionado, mesmo de livros diferentes, farão parte de todas as obras
         // solução: criar um arraylist para cada objeto de livro novo criado
        //Autor emerson = new Autor("Emerson Mello", "Brasil", LocalDate.of(1980, 3,10));
        //autores.add(emerson);

        ArrayList<Autor> autoresOutro = new ArrayList<>();
        Autor emerson = new Autor("Emerson Mello", "Brasil", LocalDate.of(1980, 3,10));
        autoresOutro.add(jean);
        autoresOutro.add(emerson);

        //arraylist passada por referencia
        Livro eraUmaVez = new Livro("32103540321354", "Era Uma Vez", autoresOutro);

        System.out.println(onceATime);
        System.out.println(eraUmaVez);
    }
}
