/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

//cd StarUML
//./opt/StarUML/staruml --no-sandbox &

public class Principal {
    public static void main(String[] args) {
        
    }
}
