/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom;

public class App {
    public static void main(String[] args) {
        /*
        1- Documentação de código com JavaDOC
        2- Teste de Unidade
         */

        Carro c = new Carro();
        c.acelerar(10);
    }
}
