/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom;

/**
 * Aula de JavaDOC
 *
 * Para verificar o arquivo html, ir na raiz do projeto, app, build, docs, index.html
 */
public class App {

    public App(){

    }

    /**
     * Classe main
     * @param args argumentos de linha de comando
     */
    public static void main(String[] args) {
        /*
        1- Documentação de código com JavaDOC
        2- Teste de Unidade
         */

        Carro c = new Carro();
        c.acelerar(10);
    }
}
