/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom;

public class App {
    public static void main(String[] args) {
        Naipe naipe;

        System.out.println("\uD83C\uDCA1");
        System.out.println("\uD83C\uDCB1");
        System.out.println("\uD83C\uDCB2");
        System.out.println();
    }
}
