/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
//        Caneta bic = new Caneta(100, "azul");
//        Caneta pencil = new Caneta("vermelha");
//        Caneta faber =  new Caneta();
//
//        bic.setNivelTinta(-500);
//        System.out.println(bic.getNivelTinta());
//
//        pencil.setNivelTinta(101);
//        System.out.println(pencil.getNivelTinta());
        Carro renegado = new Carro(20);

        System.out.println(renegado.getVelocidade());
        renegado.acelerar(200);
        System.out.println(renegado.getVelocidade());

    }
}
