/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.logging.*;

public class App {
    private static final Logger LOGGER = Logger.getLogger(App.class.getName());

    public static void main(String[] args) {
        LOGGER.setLevel(Level.SEVERE);

        LOGGER.fine("Mensagem de depuração");
        LOGGER.info("aplicação iniciada com sucesso");
        LOGGER.warning("número de matricula invalido");
        LOGGER.severe("conexão perdida com o banco de dados");
    }
}
