/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Pilha<String> pilha = new Pilha<>(10);

        System.out.println(pilha.tamanhoPilha());

        String ola = "Olá, mundo";
        try {
            pilha.adicionar(ola);
        } catch (PilhaCheiaException e) {
            throw new RuntimeException(e);
        }
        System.out.println(pilha.tamanhoPilha());

        Object variavel;
        try{
            variavel = pilha.remover();
            System.out.println(variavel);
        } catch (PilhaVaziaException e){
            throw new RuntimeException(e);
        }

        System.out.println(pilha.tamanhoPilha());

        //não posso adicionar inteiros porque é um vetor de strings
        try{
            for (int i = 0; i < 12; i++) {
                pilha.adicionar(i);
                System.out.println(pilha.tamanhoPilha());
            }
        } catch (Exception e){
            throw new RuntimeException(e);
        }

    }
}
